### ISSUE TITLE
Consider returning String not Result(String, _) for nanoid.generate

### ISSUE THREAD

**Issue by lpil** [rvcas/ids#12]
Hello!

It looks like there is no way for the user to incorrectly use the `nanoid.generate` function. It always succeeds but the programmer is forced to handle the impossible error case.

Could it instead return a string? I think this will improve the user experience.

Thanks,
Louis

**Comment by rvcas** [comment]
@lpil yes absolutely, I'll change that and release a new version. Thanks!

**Comment by lpil** [comment]
Brilliant! Thank you!
