### ISSUE TITLE
Curious about result return decision

### ISSUE THREAD

**Issue by aosasona** [rvcas/ids#19]
Forgive the horrible title but I was just curious why you have chosen to go with 

```gleam
""
|> Error
```

instead of
```gleam 
Error("")
```

**Comment by rvcas** [comment]
No particular reason, there's functionally no difference

**Comment by aosasona** [comment]
> No particular reason, there's functionally no difference

Fair enough, I am aware they are the same thing, this choice is just unusual haha, that's why I asked, thanks for answering!
