### ISSUE TITLE
Emoji rendering on Hex and Gleam Packages

### ISSUE THREAD

**Issue by rokf** [rvcas/ids#24]
Hello, the following two sites don't seem to like the emoji in the description. A `(` is rendered instead of it. Would you perhaps consider removing the emoji from the description?

- https://hex.pm/packages/ids
- https://packages.gleam.run/?search=

![CleanShot 2024-01-30 at 22 05 23](https://github.com/rvcas/ids/assets/2836852/9c8462dc-61f6-4ba7-a1a3-f1031529bc32)

![CleanShot 2024-01-30 at 22 05 39](https://github.com/rvcas/ids/assets/2836852/bb9fe5a6-2ba0-4235-8208-b3e2bae79c60)

**Comment by rvcas** [comment]
No I won't remove it. It renders just fine on the online documentation.
![image](https://github.com/rvcas/ids/assets/12070598/14de31ba-95ff-462a-a305-6786d84688b7)
