### ISSUE TITLE
Fails to build on latest gleam_stdlib

### ISSUE THREAD

**Issue by gmartsenkov** [rvcas/ids#27]
My project fails to build after adding `ids` to the dependencies list. This seems to be due to `list.at` being removed from the standard library - https://github.com/gleam-lang/stdlib/blob/main/CHANGELOG.md#v0380---2024-05-24 
I believe the alternative is to use `iterator.at`

```
error: Unknown module field
    ┌─ /Users/gogo/Development/zeus/build/packages/ids/src/ids/ulid.gleam:151:14
    │
151 │       |> list.at(index)
    │              ^^^ Did you mean `last`?
```

**Comment by gmartsenkov** [comment]
Looks like it's because you haven't pushed latest code to hex.pm. Do you mind cutting a new release and publishing to hex.pm?

**Comment by akirak** [comment]
[sprocket](https://github.com/bitbldr/sprocket), for example, fails to build due to this issue. Could you bump the release once it's ready?

**Comment by rvcas** [comment]
@gmartsenkov @akirak yes I gotchu

**Comment by rvcas** [comment]
https://github.com/rvcas/ids/releases/tag/v0.13.0

**Comment by gmartsenkov** [comment]
thank you!
