### ISSUE TITLE
Maybe streamline the API?

### ISSUE THREAD

**Issue by NicklasXYZ** [rvcas/ids#3]
When implementing the NanoID generation functionality I noticed that the generation of an UUIDv4 or cuid use function calls such as `v4()` or `gen()`, respectively. 

Would it make sense to  streamline the API by pre-pending or just using `generate` as the function name?
For example, to generate a UUIDv4 the function call would then be `uuid.generate_v4()`, while to generate a cuid the function call would be `cuid.generate()`?

I image the secure and non-secure generation of NanoIDs would use functions with names `nanoid.generate()` and `nanoid.generate_non_secure()`, respectively.

Or how do you imagine the API should be designed to align the functions in the different modules?

**Comment by rvcas** [comment]
I haven't thought about it too much. I'm not particularly concerned about having some kind of uniform API across modules. The idea is mostly to just have a convenient grouping of common unique ids that people might need. That being said I'm not against the idea either, feel free to submit these changes.
