### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by NicklasXYZ** [rvcas/ids#6]
Just a friendly reminder to maybe create a new release and update docs :-)

**Comment by rvcas** [comment]
@NicklasXYZ I'll do that today thanks

**Comment by rvcas** [comment]
@NicklasXYZ this is done now, sorry for the delay. You should be able to see the updated docs at https://hexdocs.pm/ids/

**Comment by NicklasXYZ** [comment]
Cool! Thank you :)!
